### ISSUE TITLE
Add Beetle PCE Fast to RALibretro

### ISSUE THREAD

**Issue by kdecks** [RetroAchievements/RALibretro#91] opened 2019-07-19 19:02 UTC
This is a missing core with achievement support in an effort to bring all cores that support achievements in Retroarch into RALibretro.

**Comment by Jamiras** [comment] 2019-08-31 15:25
I'm not sure what "Beetle NeoPop Fast" is. The only documented NeoGeo Pocket core available is "[Beetle NeoPop](https://docs.libretro.com/library/beetle_neopop/)", which we already support. The only other core in the buildbot that looks applicable is "fbalpha2012_neogeo_libretro".

**Comment by kdecks** [comment] 2019-08-31 17:50
I simply pulled everything from this list: https://docs.libretro.com/guides/retroachievements/

**Comment by Jamiras** [comment] 2019-12-14 15:50
in that case, this is a duplicate of #90

**Closed by Jamiras** 2019-12-14 15:50 UTC
