### ISSUE TITLE
Allow importing search results into memory inspector

### ISSUE THREAD

**Issue by PopovMark** [RetroAchievements/RALibretro#385] opened 2023-08-04 04:06 UTC
Currently, RALibRetro allows you to export the results of your RAM digging into a csv file. I believe that an opposite feature would also be helpful: to import one of said csv files into the memory inspector, so that you can then continue where you left off. That way, you can spread out any particularly hard values across multiple sessions of RAM digging. I've had cases where I've had to individually test a couple hundred addresses to find one thing, and it would be very convenient if I didn't have to lose them upon closing the emulator.

As to how it would look, I'd suggest an "Import" button next to the "Export" button in the mem inspector, which would trigger a file dialog for opening a csv file. Upon opening it, it would show the included state of memory searching in the inspector.

**Comment by Jamiras** [comment] 2023-08-05 12:42
Duplicate of https://github.com/RetroAchievements/RAIntegration/discussions/775. If you with to expound upon this idea further, please do so there.

The problem with importing the data is that it's tied to a specific frame of emulation, and the memory inspector has no way to cause the emulator to create a save state to go with the captured data.

Import would have to behave like "New Search", where the import just servers as some initial set of data, and your first filter would actually start reporting data.

**Closed** 2023-08-05 12:42 UTC
