### ISSUE TITLE
Atari 2600 integer window sizing is incorrect

### ISSUE THREAD

**Issue by rzumer** [RetroAchievements/RALibretro#167] opened 2020-02-26 02:20 UTC
Tested with Dragonstomper, scaling to an integer multiple seems to make the window much wider than it should be.

**Comment by Jamiras** [comment] 2021-04-06 15:13
Closing as not reproducible because there's no detail on "what it should be" vs. "what it is/was". It may have been fixed, or it may just be a misunderstanding. 

Dragonstomper at 2x (preserve aspect ratio on/off):
![image](https://user-images.githubusercontent.com/32680403/113734046-3ad33080-96b8-11eb-970f-c6485bf4f064.png)
![image](https://user-images.githubusercontent.com/32680403/113734061-3e66b780-96b8-11eb-8502-f6b2f090e11f.png)

**Closed by Jamiras** 2021-04-06 15:13 UTC
Labels: bug
